/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GrantedAuthority } from '../models/granted-authority';
import { Task } from '../models/task';
import { Token } from '../models/token';
export interface Users {
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  authorities?: Array<GrantedAuthority>;
  credentialsNonExpired?: boolean;
  email?: string;
  enabled?: boolean;
  id?: number;
  password?: string;
  role?: 'USER' | 'ADMIN';
  tasks?: Array<Task>;
  tokens?: Array<Token>;
  username?: string;
}
