/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Users } from '../../models/users';

export interface Getuser$Params {
  Username: string;
}

export function getuser(http: HttpClient, rootUrl: string, params: Getuser$Params, context?: HttpContext): Observable<StrictHttpResponse<Users>> {
  const rb = new RequestBuilder(rootUrl, getuser.PATH, 'get');
  if (params) {
    rb.query('Username', params.Username, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Users>;
    })
  );
}

getuser.PATH = '/users/getuser';
