/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createTask } from '../fn/task-controller/create-task';
import { CreateTask$Params } from '../fn/task-controller/create-task';
import { deleteTask } from '../fn/task-controller/delete-task';
import { DeleteTask$Params } from '../fn/task-controller/delete-task';
import { getAllTasksByUser } from '../fn/task-controller/get-all-tasks-by-user';
import { GetAllTasksByUser$Params } from '../fn/task-controller/get-all-tasks-by-user';
import { getTodayTasks } from '../fn/task-controller/get-today-tasks';
import { GetTodayTasks$Params } from '../fn/task-controller/get-today-tasks';
import { getUpcomingTasks } from '../fn/task-controller/get-upcoming-tasks';
import { GetUpcomingTasks$Params } from '../fn/task-controller/get-upcoming-tasks';
import { Task } from '../models/task';
import { updateTask } from '../fn/task-controller/update-task';
import { UpdateTask$Params } from '../fn/task-controller/update-task';

@Injectable({ providedIn: 'root' })
export class TaskControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateTask()` */
  static readonly UpdateTaskPath = '/api/tasks/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateTask()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTask$Response(params: UpdateTask$Params, context?: HttpContext): Observable<StrictHttpResponse<Task>> {
    return updateTask(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateTask$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateTask(params: UpdateTask$Params, context?: HttpContext): Observable<Task> {
    return this.updateTask$Response(params, context).pipe(
      map((r: StrictHttpResponse<Task>): Task => r.body)
    );
  }

  /** Path part for operation `deleteTask()` */
  static readonly DeleteTaskPath = '/api/tasks/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteTask()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTask$Response(params: DeleteTask$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteTask(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteTask$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteTask(params: DeleteTask$Params, context?: HttpContext): Observable<void> {
    return this.deleteTask$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAllTasksByUser()` */
  static readonly GetAllTasksByUserPath = '/api/tasks';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllTasksByUser()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTasksByUser$Response(params: GetAllTasksByUser$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Task>>> {
    return getAllTasksByUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllTasksByUser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllTasksByUser(params: GetAllTasksByUser$Params, context?: HttpContext): Observable<Array<Task>> {
    return this.getAllTasksByUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Task>>): Array<Task> => r.body)
    );
  }

  /** Path part for operation `createTask()` */
  static readonly CreateTaskPath = '/api/tasks';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createTask()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTask$Response(params: CreateTask$Params, context?: HttpContext): Observable<StrictHttpResponse<Task>> {
    return createTask(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createTask$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createTask(params: CreateTask$Params, context?: HttpContext): Observable<Task> {
    return this.createTask$Response(params, context).pipe(
      map((r: StrictHttpResponse<Task>): Task => r.body)
    );
  }

  /** Path part for operation `getUpcomingTasks()` */
  static readonly GetUpcomingTasksPath = '/api/tasks/upcoming';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUpcomingTasks()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUpcomingTasks$Response(params?: GetUpcomingTasks$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Task>>> {
    return getUpcomingTasks(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUpcomingTasks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUpcomingTasks(params?: GetUpcomingTasks$Params, context?: HttpContext): Observable<Array<Task>> {
    return this.getUpcomingTasks$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Task>>): Array<Task> => r.body)
    );
  }

  /** Path part for operation `getTodayTasks()` */
  static readonly GetTodayTasksPath = '/api/tasks/today';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getTodayTasks()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTodayTasks$Response(params?: GetTodayTasks$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Task>>> {
    return getTodayTasks(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getTodayTasks$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getTodayTasks(params?: GetTodayTasks$Params, context?: HttpContext): Observable<Array<Task>> {
    return this.getTodayTasks$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<Task>>): Array<Task> => r.body)
    );
  }

}
