/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getuser } from '../fn/users-controller/getuser';
import { Getuser$Params } from '../fn/users-controller/getuser';
import { Users } from '../models/users';

@Injectable({ providedIn: 'root' })
export class UsersControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getuser()` */
  static readonly GetuserPath = '/users/getuser';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getuser()` instead.
   *
   * This method doesn't expect any request body.
   */
  getuser$Response(params: Getuser$Params, context?: HttpContext): Observable<StrictHttpResponse<Users>> {
    return getuser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getuser$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getuser(params: Getuser$Params, context?: HttpContext): Observable<Users> {
    return this.getuser$Response(params, context).pipe(
      map((r: StrictHttpResponse<Users>): Users => r.body)
    );
  }

}
